name: UndroppableDroppables
main: com.icomeinpieces.UndroppableDroppables.UndroppableDroppables
version: 1.12
description: makes most things that don't drop something like bookcases well drop something like a bookcase
author: icomeinpieces
commands:
    udreload:
        description: reloads the configuration file
        usage: /<command>