name: UndroppableDroppables
main: com.icomeinpieces.UndroppableDroppables.UndroppableDroppables
version: 1.5
description: want to pick up that Glowstone as Glowstone, or that bookcase but can't well now you can. pick up glowstone, ice, bookcases, glass, both types of stairs, and grass.
author: icomeinpieces