name: UndroppableDroppables
main: com.icomeinpieces.UndroppableDroppables.UndroppableDroppables
version: 1.3
description: want to pick up that Glowstone as Glowstone, or that bookcase but can't well now you can. pick up glowstone, ice, bookcases, glass, and both types of stairs.
author: icomeinpieces